---
title: "Tidy data"
output: github_document
---

```{r}
library(tidyverse)
```

## Lets tidy some data 

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```

Okay, lets tidy!

```{r, eval=FALSE}
pulse_tidy_df = 
  pulse_df |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", 
    names_prefix = "bdi_score_", 
    values_to = "bdi_score"
  ) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
```

In theory these top two blocks would just be combined into one 

lets practice!

Import litters data, keep columns litter number and gd weights and tidy it 

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na=c(".", "", "NA")) |>
  janitor::clean_names() |>
  select(litter_number, gd0_weight, gd18_weight) |>
  pivot_longer(
    gd0_weight:gd18_weight, 
    names_to = "gd",
    values_to = "weight"
  ) |>
  mutate(
    gd_number = case_match(
      gd, 
      "gd0_weight" ~ 0, 
      "gd18_weight" ~ 18 
    )
  )
```

## Deliberately untidy data 

```{r}
analysis_df = 
  tibble(
    groups = c("treatment", "treatment", "placebo", "placebo"), 
    time = c("pre", "post", "pre", "post"), 
    mean_outcome = c(4, 8, 3.5, 3.6)
  )
```

Untidy this dataset for human readbility 

```{r}
analysis_df |>
    pivot_wider(
      names_from = time, 
      values_from = mean_outcome
    ) |>
    knitr::kable()
```

## bind some rows 

first, import each LOTR movie table

```{r}
followship_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie="fellowship")

two_towers_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie="two towers")

return_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie="return of the king")
```

next put all of these together and tidy 

```{r}
lotr_df = 
  bind_rows(followship_df, two_towers_df, return_df) |>
  janitor::clean_names() |>
  relocate(movie) |>
  pivot_longer(
    female:male, 
    names_to = "gender", 
    values_to = "words"
  )
```


